#ifndef QUARD_STAR_H_
#define QUARD_STAR_H_

#include "riscv-reg.h"

#ifdef __ASSEMBLER__
#define CONS(NUM, TYPE)NUM
#else
#define CONS(NUM, TYPE)NUM##TYPE
#endif /* __ASSEMBLER__ */

#define PRIM_HART			7

#define NS16550_ADDR		CONS(0x10002000, UL)
#define PLIC_ADDR            CONS(0x0c000000, UL)
#define GPIO_ADDR            CONS(0x10009000, UL)
#define DEMOCHAR_ADDR        CONS(0x10015000, UL)
#define DOORBELL_ADDR        CONS(0x10016000, UL)

#define QUARD_STAR_DOORBELL_L2R_IRQ    60U
#define QUARD_STAR_DOORBELL_R2L_IRQ    61U
#define QUARD_STAR_PLIC_CONTEXT_ID_S   ((PRIM_HART * 2U) + 1U)

#define QUARD_STAR_PLIC_PRIORITY_BASE   0x00000004UL
#define QUARD_STAR_PLIC_ENABLE_BASE     0x00002000UL
#define QUARD_STAR_PLIC_ENABLE_STRIDE   0x00000080UL
#define QUARD_STAR_PLIC_CONTEXT_BASE    0x00200000UL
#define QUARD_STAR_PLIC_CONTEXT_STRIDE  0x00001000UL

#define QUARD_STAR_PLIC_SOURCE_PRIO(irq) \
    (PLIC_ADDR + QUARD_STAR_PLIC_PRIORITY_BASE + ((irq) * 4UL))
#define QUARD_STAR_PLIC_ENABLE_WORD(ctx, word) \
    (PLIC_ADDR + QUARD_STAR_PLIC_ENABLE_BASE + \
     ((ctx) * QUARD_STAR_PLIC_ENABLE_STRIDE) + ((word) * 4UL))
#define QUARD_STAR_PLIC_CONTEXT_THRESHOLD(ctx) \
    (PLIC_ADDR + QUARD_STAR_PLIC_CONTEXT_BASE + \
     ((ctx) * QUARD_STAR_PLIC_CONTEXT_STRIDE) + 0x0UL)
#define QUARD_STAR_PLIC_CONTEXT_CLAIM(ctx) \
    (PLIC_ADDR + QUARD_STAR_PLIC_CONTEXT_BASE + \
     ((ctx) * QUARD_STAR_PLIC_CONTEXT_STRIDE) + 0x4UL)

#ifndef __ASSEMBLER__

#endif /* __ASSEMBLER__ */

#endif /* QUARD_STAR_H_ */
